### ISSUE TITLE
Asynchronous tar extraction

### ISSUE THREAD

**Issue by zkat** [entropic-dev/ds#43]
For performance reasons, we could -really- use an async version of [the `tar` crate](https://crates.io/crates/tar) that is able to work on `AsyncRead`s and `Stream`s.

**Comment by superhawk610** [comment]
Looking into this, I'll update as I can.

**Comment by zkat** [comment]
Thank you!

**Comment by superhawk610** [comment]
Just to clarify, are we looking for convenience methods on `tar` for working with async data sources or more of a full-blown streaming content listing/extraction implementation?

**Comment by zkat** [comment]
Ideally, we would be able to async stream data into it, then iterate over entries from a Stream, and be able to pipe the extracted data somewhere from there.

So tl;dr more of a full blown async tar library.

**Comment by zkat** [comment]
@superhawk610 are you still interested in doing this one? I'm thinking of picking it up myself.

**Comment by superhawk610** [comment]
If you want it, please take it! I’m a new Rustling and more looking to learn than anything else, I’ve been playing around with this but not making any fast progress. Taking a look at your approach would be just as helpful!

Let me know if I can do anything else to help.

**Comment by zkat** [comment]
@superhawk610 yeah it turns out this is actually fairly hard. I have a fork going at https://github.com/zkat/tar-rs/tree/zkat/async but I need to go bit by bit because it's all AsyncRead/Write and Stream impls that I... still don't get how to do.

**Comment by zkat** [comment]
https://crates.io/crates/async-tar has been released, so this is done! 🎉
